services:
  runner:
    image: data.forgejo.org/forgejo/runner:12
    container_name: forgejo-runner
    user: root
    restart: unless-stopped
    volumes:
      - ./runner-config.yml:/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: forgejo-runner daemon --config /config.yml
